apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      run: demo
  replicas: 2
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: bushu123/kaniko1111:4
        ports:
        - containerPort: 80

